title: "Going Deeper"
language: und
menu: "Going Deeper"
weight: 4
menu_name: menu-developer-guide
abstract: "Going deeper inside the Pydio architecture, from server to web application, and start hacking!"
slug: going-deeper
